### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by Eximinati** [zunjae/nayto.app#1]
Can you add proxy option in it bcoz some of countries hentai sites are ban so proxy will make it easier, i love your app make a login and download option if possible!  @zunjae

**Comment by zunjae** [comment]
Please use the Discord server for requests

**Comment by Eximinati** [comment]
> Please use the Discord server for requests

Can i have link?

**Comment by Eximinati** [comment]
Give me discord link, bcoz anYme X link is expired
